//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.18.0
//     from Assets/Settings/RythemGameKey.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Settings/RythemGameKey.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @InputButtons: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @InputButtons()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""RythemGameKey"",
    ""maps"": [
        {
            ""name"": ""4k"",
            ""id"": ""ce89ec75-bbf7-415b-83a5-bf9976fced20"",
            ""actions"": [
                {
                    ""name"": ""butten1"",
                    ""type"": ""Button"",
                    ""id"": ""2b1b01f1-31b3-488f-ad36-2c8e9684a3f4"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""butten2"",
                    ""type"": ""Button"",
                    ""id"": ""d128a569-6c6f-46ef-a3fc-733d42ce78f6"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""butten3"",
                    ""type"": ""Button"",
                    ""id"": ""f4f3bfc8-a93b-47b3-90f3-feb3ebc770ef"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""butten4"",
                    ""type"": ""Button"",
                    ""id"": ""356b2db4-0c9b-491d-9366-840cdb8081d9"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""buttenL"",
                    ""type"": ""Button"",
                    ""id"": ""4e2e8ef0-8175-46a2-b703-47e92e22aeb0"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""buttenR"",
                    ""type"": ""Button"",
                    ""id"": ""576c2922-a3fc-4230-9d0f-fc9bf25f6d65"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""6a8822b1-c2cd-4e75-b501-af768ab898c9"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""butten1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cd063c96-365a-42ee-9b79-71b33b628656"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""butten2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7ba606ac-3a23-4057-b884-f64463e473f7"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""butten3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1506ce65-28e2-400d-acc5-32ed76afd604"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""butten4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3a91e907-7bbe-41e6-a81c-c176dcf7ccbc"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""buttenL"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""529e6915-60dd-4aff-af58-ae619da30e4c"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""buttenR"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""6k"",
            ""id"": ""a92ef714-0ad1-4806-9f09-3e6ead006942"",
            ""actions"": [
                {
                    ""name"": ""butten1"",
                    ""type"": ""Button"",
                    ""id"": ""be12ca8e-2ae1-4de3-90f3-0b29a3779ca3"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""butten2"",
                    ""type"": ""Button"",
                    ""id"": ""e895e30e-aa69-4f0d-ae92-980bf871c574"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""butten3"",
                    ""type"": ""Button"",
                    ""id"": ""12364dda-ba98-4c93-b8cb-e03d96fa0bf1"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""butten4"",
                    ""type"": ""Button"",
                    ""id"": ""2b7b6d29-d440-46b2-bb34-844f9b2abf46"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""butten5"",
                    ""type"": ""Button"",
                    ""id"": ""178a28e7-743c-4295-ac46-bb6b5b060b8e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""butten6"",
                    ""type"": ""Button"",
                    ""id"": ""de8352cf-f6e9-4751-9b49-e2d384176ac7"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""buttenL"",
                    ""type"": ""Button"",
                    ""id"": ""7733bb61-7c28-4407-b852-518d75343e65"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""buttenR"",
                    ""type"": ""Button"",
                    ""id"": ""7f18fc77-fe59-4105-8b20-e7fc74f02e46"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""5874ea2e-d6b8-4397-9600-63fbfa7554b0"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""butten1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9593a6c2-b57b-4451-9cea-bae5adfaa1fd"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""butten2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8aa02e56-9d91-413d-9b9d-fef0baadea09"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""butten3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dd741682-344b-4026-8623-412c26017219"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""butten4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1712c050-4287-421c-9b3f-5aa5c9f56b4d"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""butten5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""10f7d22e-8c7d-4a71-a17e-f773e414058d"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""butten6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6d40df8b-d171-4b73-9242-cd07402c76cd"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""buttenL"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""72f5ac4a-210f-4eaa-af9f-74db84297583"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""buttenR"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // 4k
        m__4k = asset.FindActionMap("4k", throwIfNotFound: true);
        m__4k_butten1 = m__4k.FindAction("butten1", throwIfNotFound: true);
        m__4k_butten2 = m__4k.FindAction("butten2", throwIfNotFound: true);
        m__4k_butten3 = m__4k.FindAction("butten3", throwIfNotFound: true);
        m__4k_butten4 = m__4k.FindAction("butten4", throwIfNotFound: true);
        m__4k_buttenL = m__4k.FindAction("buttenL", throwIfNotFound: true);
        m__4k_buttenR = m__4k.FindAction("buttenR", throwIfNotFound: true);
        // 6k
        m__6k = asset.FindActionMap("6k", throwIfNotFound: true);
        m__6k_butten1 = m__6k.FindAction("butten1", throwIfNotFound: true);
        m__6k_butten2 = m__6k.FindAction("butten2", throwIfNotFound: true);
        m__6k_butten3 = m__6k.FindAction("butten3", throwIfNotFound: true);
        m__6k_butten4 = m__6k.FindAction("butten4", throwIfNotFound: true);
        m__6k_butten5 = m__6k.FindAction("butten5", throwIfNotFound: true);
        m__6k_butten6 = m__6k.FindAction("butten6", throwIfNotFound: true);
        m__6k_buttenL = m__6k.FindAction("buttenL", throwIfNotFound: true);
        m__6k_buttenR = m__6k.FindAction("buttenR", throwIfNotFound: true);
    }

    ~@InputButtons()
    {
        UnityEngine.Debug.Assert(!m__4k.enabled, "This will cause a leak and performance issues, InputButtons._4k.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m__6k.enabled, "This will cause a leak and performance issues, InputButtons._6k.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // 4k
    private readonly InputActionMap m__4k;
    private List<I_4kActions> m__4kActionsCallbackInterfaces = new List<I_4kActions>();
    private readonly InputAction m__4k_butten1;
    private readonly InputAction m__4k_butten2;
    private readonly InputAction m__4k_butten3;
    private readonly InputAction m__4k_butten4;
    private readonly InputAction m__4k_buttenL;
    private readonly InputAction m__4k_buttenR;
    /// <summary>
    /// Provides access to input actions defined in input action map "4k".
    /// </summary>
    public struct _4kActions
    {
        private @InputButtons m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public _4kActions(@InputButtons wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "_4k/butten1".
        /// </summary>
        public InputAction @butten1 => m_Wrapper.m__4k_butten1;
        /// <summary>
        /// Provides access to the underlying input action "_4k/butten2".
        /// </summary>
        public InputAction @butten2 => m_Wrapper.m__4k_butten2;
        /// <summary>
        /// Provides access to the underlying input action "_4k/butten3".
        /// </summary>
        public InputAction @butten3 => m_Wrapper.m__4k_butten3;
        /// <summary>
        /// Provides access to the underlying input action "_4k/butten4".
        /// </summary>
        public InputAction @butten4 => m_Wrapper.m__4k_butten4;
        /// <summary>
        /// Provides access to the underlying input action "_4k/buttenL".
        /// </summary>
        public InputAction @buttenL => m_Wrapper.m__4k_buttenL;
        /// <summary>
        /// Provides access to the underlying input action "_4k/buttenR".
        /// </summary>
        public InputAction @buttenR => m_Wrapper.m__4k_buttenR;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m__4k; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="_4kActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(_4kActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="_4kActions" />
        public void AddCallbacks(I_4kActions instance)
        {
            if (instance == null || m_Wrapper.m__4kActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m__4kActionsCallbackInterfaces.Add(instance);
            @butten1.started += instance.OnButten1;
            @butten1.performed += instance.OnButten1;
            @butten1.canceled += instance.OnButten1;
            @butten2.started += instance.OnButten2;
            @butten2.performed += instance.OnButten2;
            @butten2.canceled += instance.OnButten2;
            @butten3.started += instance.OnButten3;
            @butten3.performed += instance.OnButten3;
            @butten3.canceled += instance.OnButten3;
            @butten4.started += instance.OnButten4;
            @butten4.performed += instance.OnButten4;
            @butten4.canceled += instance.OnButten4;
            @buttenL.started += instance.OnButtenL;
            @buttenL.performed += instance.OnButtenL;
            @buttenL.canceled += instance.OnButtenL;
            @buttenR.started += instance.OnButtenR;
            @buttenR.performed += instance.OnButtenR;
            @buttenR.canceled += instance.OnButtenR;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="_4kActions" />
        private void UnregisterCallbacks(I_4kActions instance)
        {
            @butten1.started -= instance.OnButten1;
            @butten1.performed -= instance.OnButten1;
            @butten1.canceled -= instance.OnButten1;
            @butten2.started -= instance.OnButten2;
            @butten2.performed -= instance.OnButten2;
            @butten2.canceled -= instance.OnButten2;
            @butten3.started -= instance.OnButten3;
            @butten3.performed -= instance.OnButten3;
            @butten3.canceled -= instance.OnButten3;
            @butten4.started -= instance.OnButten4;
            @butten4.performed -= instance.OnButten4;
            @butten4.canceled -= instance.OnButten4;
            @buttenL.started -= instance.OnButtenL;
            @buttenL.performed -= instance.OnButtenL;
            @buttenL.canceled -= instance.OnButtenL;
            @buttenR.started -= instance.OnButtenR;
            @buttenR.performed -= instance.OnButtenR;
            @buttenR.canceled -= instance.OnButtenR;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="_4kActions.UnregisterCallbacks(I_4kActions)" />.
        /// </summary>
        /// <seealso cref="_4kActions.UnregisterCallbacks(I_4kActions)" />
        public void RemoveCallbacks(I_4kActions instance)
        {
            if (m_Wrapper.m__4kActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="_4kActions.AddCallbacks(I_4kActions)" />
        /// <seealso cref="_4kActions.RemoveCallbacks(I_4kActions)" />
        /// <seealso cref="_4kActions.UnregisterCallbacks(I_4kActions)" />
        public void SetCallbacks(I_4kActions instance)
        {
            foreach (var item in m_Wrapper.m__4kActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m__4kActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="_4kActions" /> instance referencing this action map.
    /// </summary>
    public _4kActions @_4k => new _4kActions(this);

    // 6k
    private readonly InputActionMap m__6k;
    private List<I_6kActions> m__6kActionsCallbackInterfaces = new List<I_6kActions>();
    private readonly InputAction m__6k_butten1;
    private readonly InputAction m__6k_butten2;
    private readonly InputAction m__6k_butten3;
    private readonly InputAction m__6k_butten4;
    private readonly InputAction m__6k_butten5;
    private readonly InputAction m__6k_butten6;
    private readonly InputAction m__6k_buttenL;
    private readonly InputAction m__6k_buttenR;
    /// <summary>
    /// Provides access to input actions defined in input action map "6k".
    /// </summary>
    public struct _6kActions
    {
        private @InputButtons m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public _6kActions(@InputButtons wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "_6k/butten1".
        /// </summary>
        public InputAction @butten1 => m_Wrapper.m__6k_butten1;
        /// <summary>
        /// Provides access to the underlying input action "_6k/butten2".
        /// </summary>
        public InputAction @butten2 => m_Wrapper.m__6k_butten2;
        /// <summary>
        /// Provides access to the underlying input action "_6k/butten3".
        /// </summary>
        public InputAction @butten3 => m_Wrapper.m__6k_butten3;
        /// <summary>
        /// Provides access to the underlying input action "_6k/butten4".
        /// </summary>
        public InputAction @butten4 => m_Wrapper.m__6k_butten4;
        /// <summary>
        /// Provides access to the underlying input action "_6k/butten5".
        /// </summary>
        public InputAction @butten5 => m_Wrapper.m__6k_butten5;
        /// <summary>
        /// Provides access to the underlying input action "_6k/butten6".
        /// </summary>
        public InputAction @butten6 => m_Wrapper.m__6k_butten6;
        /// <summary>
        /// Provides access to the underlying input action "_6k/buttenL".
        /// </summary>
        public InputAction @buttenL => m_Wrapper.m__6k_buttenL;
        /// <summary>
        /// Provides access to the underlying input action "_6k/buttenR".
        /// </summary>
        public InputAction @buttenR => m_Wrapper.m__6k_buttenR;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m__6k; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="_6kActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(_6kActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="_6kActions" />
        public void AddCallbacks(I_6kActions instance)
        {
            if (instance == null || m_Wrapper.m__6kActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m__6kActionsCallbackInterfaces.Add(instance);
            @butten1.started += instance.OnButten1;
            @butten1.performed += instance.OnButten1;
            @butten1.canceled += instance.OnButten1;
            @butten2.started += instance.OnButten2;
            @butten2.performed += instance.OnButten2;
            @butten2.canceled += instance.OnButten2;
            @butten3.started += instance.OnButten3;
            @butten3.performed += instance.OnButten3;
            @butten3.canceled += instance.OnButten3;
            @butten4.started += instance.OnButten4;
            @butten4.performed += instance.OnButten4;
            @butten4.canceled += instance.OnButten4;
            @butten5.started += instance.OnButten5;
            @butten5.performed += instance.OnButten5;
            @butten5.canceled += instance.OnButten5;
            @butten6.started += instance.OnButten6;
            @butten6.performed += instance.OnButten6;
            @butten6.canceled += instance.OnButten6;
            @buttenL.started += instance.OnButtenL;
            @buttenL.performed += instance.OnButtenL;
            @buttenL.canceled += instance.OnButtenL;
            @buttenR.started += instance.OnButtenR;
            @buttenR.performed += instance.OnButtenR;
            @buttenR.canceled += instance.OnButtenR;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="_6kActions" />
        private void UnregisterCallbacks(I_6kActions instance)
        {
            @butten1.started -= instance.OnButten1;
            @butten1.performed -= instance.OnButten1;
            @butten1.canceled -= instance.OnButten1;
            @butten2.started -= instance.OnButten2;
            @butten2.performed -= instance.OnButten2;
            @butten2.canceled -= instance.OnButten2;
            @butten3.started -= instance.OnButten3;
            @butten3.performed -= instance.OnButten3;
            @butten3.canceled -= instance.OnButten3;
            @butten4.started -= instance.OnButten4;
            @butten4.performed -= instance.OnButten4;
            @butten4.canceled -= instance.OnButten4;
            @butten5.started -= instance.OnButten5;
            @butten5.performed -= instance.OnButten5;
            @butten5.canceled -= instance.OnButten5;
            @butten6.started -= instance.OnButten6;
            @butten6.performed -= instance.OnButten6;
            @butten6.canceled -= instance.OnButten6;
            @buttenL.started -= instance.OnButtenL;
            @buttenL.performed -= instance.OnButtenL;
            @buttenL.canceled -= instance.OnButtenL;
            @buttenR.started -= instance.OnButtenR;
            @buttenR.performed -= instance.OnButtenR;
            @buttenR.canceled -= instance.OnButtenR;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="_6kActions.UnregisterCallbacks(I_6kActions)" />.
        /// </summary>
        /// <seealso cref="_6kActions.UnregisterCallbacks(I_6kActions)" />
        public void RemoveCallbacks(I_6kActions instance)
        {
            if (m_Wrapper.m__6kActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="_6kActions.AddCallbacks(I_6kActions)" />
        /// <seealso cref="_6kActions.RemoveCallbacks(I_6kActions)" />
        /// <seealso cref="_6kActions.UnregisterCallbacks(I_6kActions)" />
        public void SetCallbacks(I_6kActions instance)
        {
            foreach (var item in m_Wrapper.m__6kActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m__6kActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="_6kActions" /> instance referencing this action map.
    /// </summary>
    public _6kActions @_6k => new _6kActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "4k" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="_4kActions.AddCallbacks(I_4kActions)" />
    /// <seealso cref="_4kActions.RemoveCallbacks(I_4kActions)" />
    public interface I_4kActions
    {
        /// <summary>
        /// Method invoked when associated input action "butten1" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnButten1(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "butten2" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnButten2(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "butten3" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnButten3(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "butten4" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnButten4(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "buttenL" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnButtenL(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "buttenR" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnButtenR(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "6k" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="_6kActions.AddCallbacks(I_6kActions)" />
    /// <seealso cref="_6kActions.RemoveCallbacks(I_6kActions)" />
    public interface I_6kActions
    {
        /// <summary>
        /// Method invoked when associated input action "butten1" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnButten1(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "butten2" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnButten2(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "butten3" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnButten3(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "butten4" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnButten4(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "butten5" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnButten5(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "butten6" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnButten6(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "buttenL" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnButtenL(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "buttenR" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnButtenR(InputAction.CallbackContext context);
    }
}
